USE master
IF DB_ID('HolidayDB') IS NOT NULL
BEGIN
		ALTER DATABASE HolidayDB SET SINGLE_USER WITH ROLLBACK IMMEDIATE
		DROP DATABASE HolidayDB
		
END

-- Drop the 'Holiday' table
IF OBJECT_ID('Holidays') IS NOT NULL
BEGIN
    DROP TABLE Holiday;
END

-- Drop the 'Birth' table
IF OBJECT_ID('Birth') IS NOT NULL
BEGIN
    DROP TABLE Birth;
END

-- Create Database
CREATE DATABASE HolidayDB;

USE HolidayDB


--CREATE HOLIDAY TABLE
CREATE TABLE Holiday(
ID INT IDENTITY(1,1) PRIMARY KEY,
[Name] NVARCHAR(50) NOT NULL,
[Date] DATE NOT NULL
);

CREATE TABLE Birth(
ID INT IDENTITY(1,1) PRIMARY KEY,
[Name] NVARCHAR(50) NOT NULL,
[Birth] DATE NOT NULL
);