// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MærkeDag.Data;

#nullable disable

namespace MærkeDag.Migrations
{
    [DbContext(typeof(HolidayDbContext))]
    partial class HolidayDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MærkeDag.Data.Birth", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("Birthday")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Birth");
                });

            modelBuilder.Entity("MærkeDag.Data.Holiday", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Holiday");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Date = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Nytårsdag"
                        },
                        new
                        {
                            ID = 2,
                            Date = new DateTime(2023, 4, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Skærtorsdag"
                        },
                        new
                        {
                            ID = 3,
                            Date = new DateTime(2023, 4, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Langfredag"
                        },
                        new
                        {
                            ID = 4,
                            Date = new DateTime(2023, 4, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Påskedag"
                        },
                        new
                        {
                            ID = 5,
                            Date = new DateTime(2023, 4, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "2. Påskedag"
                        },
                        new
                        {
                            ID = 6,
                            Date = new DateTime(2023, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Store bededag"
                        },
                        new
                        {
                            ID = 7,
                            Date = new DateTime(2023, 5, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Kristi Himmelfartsdag"
                        },
                        new
                        {
                            ID = 8,
                            Date = new DateTime(2023, 5, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Banklukkedag"
                        },
                        new
                        {
                            ID = 9,
                            Date = new DateTime(2023, 5, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Pinsedag"
                        },
                        new
                        {
                            ID = 10,
                            Date = new DateTime(2023, 5, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "2. Pinsedag"
                        },
                        new
                        {
                            ID = 11,
                            Date = new DateTime(2023, 6, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Grundlovsdag"
                        },
                        new
                        {
                            ID = 12,
                            Date = new DateTime(2023, 12, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Juleaftensdag"
                        },
                        new
                        {
                            ID = 13,
                            Date = new DateTime(2023, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Juledag / 1. juledag"
                        },
                        new
                        {
                            ID = 14,
                            Date = new DateTime(2023, 12, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "2. juledag"
                        },
                        new
                        {
                            ID = 15,
                            Date = new DateTime(2023, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Nytårsaftensdag"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
